config/routes.rb
Rails.application.routes.draw do

  root 'learning_propositions#index'
  devise_for :users

  resources :learning_propositions, only: [:index, :show, :new, :create, :destroy] do
    resources :interests, only: [:new, :create]
  end
end

app/models/interest.rb
class Interest < ActiveRecord::Base
  belongs_to :learning_proposition
  validates :name, :email, :phone, :roles_mask, presence: true
end

app/models/learning_proposition.rb
class LearningProposition < ActiveRecord::Base
    has_many :interests
    validates :name, :session_date, :location, :min_attendees, :max_attendees, :password, :description, presence: true
    validates :min_attendees, :max_attendees, numericality: { only_integer: true, greater_than_or_equal_to: 2 }
    validates :name, :location, length: {minimum:5}

    def safe_destroy(password)
        if password == self.password
          self.destroy
          return true
        end
        return false
    end

    def self.find_open
      where("session_date > ?", DateTime.now).order(:session_date)
    end

    def self.find_close
      where("session_date <= ?", DateTime.now).order(session_date: :desc)
    end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  before_action :set_interest, only: [:show, :edit, :update, :destroy]
  before_action :set_learning_proposition, only: [:show, :edit, :update, :destroy, :new, :create]

  # GET /interests
  # GET /interests.json
  def index
    @interests = Interest.all
  end

  # GET /interests/1
  # GET /interests/1.json
  def show
  end

  # GET /interests/new
  def new
    @interest = Interest.new
  end

  # GET /interests/1/edit
  def edit
  end

  # POST /interests
  # POST /interests.json
  def create
    @interest = Interest.new(interest_params)
    @interest.learning_proposition = @learning_proposition
    respond_to do |format|
      if @interest.save
        format.html { redirect_to @learning_proposition, notice: 'Interesse foi criado com sucesso.' }

      else
        format.html { render :new }

      end
    end
  end

  # PATCH/PUT /interests/1
  # PATCH/PUT /interests/1.json
  def update
    respond_to do |format|
      if @interest.update(interest_params)
        format.html { redirect_to @learning_proposition, notice: 'Interesse foi atualizado.' }

      else
        format.html { render :edit }

      end
    end
  end

  # DELETE /interests/1
  # DELETE /interests/1.json
  def destroy
    @interest.destroy
    respond_to do |format|
      format.html { redirect_to interests_url, notice: 'Interesse foi deletado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interest
      @interest = Interest.find(params[:id])
    end

    def set_learning_proposition
      @learning_proposition = LearningProposition.find(params[:learning_proposition_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def interest_params
      params.require(:interest).permit(:name, :email, :phone, :roles_mask, :learning_propositions_id)
    end
end

app/controllers/learning_propositions_controller.rb
class LearningPropositionsController < ApplicationController
  def index
    @learning_propositions_open = LearningProposition.find_open
    @learning_propositions_close = LearningProposition.find_close
  end

  def show
    @learning_proposition = LearningProposition.find(params[:id])
  end

  def new
    @learning_proposition = LearningProposition.new

  end

  def create
    @learning_proposition = LearningProposition.new(learning_proposition_params)
    respond_to do |format|
      if @learning_proposition.save
        format.html { redirect_to @learning_proposition, notice: 'Proposta foi criada com sucesso.' }

      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @learning_proposition = LearningProposition.find(delete_learning_proposition_params[:id])
    @learning_proposition.safe_destroy(delete_learning_proposition_params[:password])
    redirect_to learning_propositions_path
  end

  private
  def learning_proposition_params
    params.require(:learning_proposition).permit(:name, :description, :min_attendees, :max_attendees, :location, :session_date, :password)
  end

  def delete_learning_proposition_params
    params.require(:learning_proposition).permit(:password, :id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/learning_propositions_helper.rb
module LearningPropositionsHelper
end

app/views/interests/_form.html.haml
= simple_form_for([@learning_proposition, @interest]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :email
    = f.input :phone
    .btn-group{"data-toggle" => "buttons"}
      %label.btn.btn-primary
        = f.radio_button :roles_mask, 1
        Aluno
      %label.btn.btn-primary
        = f.radio_button :roles_mask, 2
        Mestre
  %p
  .form-actions
    = f.button :submit , class: "btn btn-success"

app/views/interests/edit.html.haml
%h1 Editing interest

= render 'form'

= link_to 'Show', @interest
\|
= link_to 'Back', interests_path

app/views/interests/index.html.haml
%h1 Listing interests

%table
  %thead
    %tr
      %th Name
      %th Email
      %th Phone
      %th Roles mask
      %th Learning propositions
      %th
      %th
      %th

  %tbody
    - @interests.each do |interest|
      %tr
        %td= interest.name
        %td= interest.email
        %td= interest.phone
        %td= interest.roles_mask
        %td= interest.learning_propositions_id
        %td= link_to 'Show', interest
        %td= link_to 'Edit', edit_interest_path(interest)
        %td= link_to 'Destroy', interest, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Interest', new_interest_path

app/views/interests/new.html.haml
%h1 Confirme seu interesse

= render 'form'
%p
= link_to 'voltar', learning_proposition_path(@learning_proposition), class: "btn btn-default"

app/views/interests/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @interest.name
%p
  %b Email:
  = @interest.email
%p
  %b Phone:
  = @interest.phone
%p
  %b Roles mask:
  = @interest.roles_mask
%p
  %b Learning propositions:
  = @interest.learning_propositions_id

= link_to 'Edit', edit_interest_path(@interest)
\|
= link_to 'Back', interests_path

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_header.html.erb
<div class="topo">
  <div class="row">
    <div class="col-md-8">
    <div class="logo">
      <%= link_to image_tag("logo.png"), learning_propositions_path %>
    </div>
    </div>

    <div class="col-md-4">
    <div class="links">
      <%= link_to "HOME", learning_propositions_path %>
      <%= link_to "Criar Sessão", new_learning_proposition_path %>
    </div>
    </div>
  </div>
  </div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Teias De Aprendizagem'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Teias De Aprendizagem'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %main{:role => "main"}
      .container
        = render 'layouts/navigation_header'
        = render 'layouts/messages'

        = yield

app/views/learning_propositions/_list.html.erb
    <% learning_propositions.each do |learning_proposition| %>
        <div class="jumbotron col-xs-6 col-md-5 list_index">
          <h1><%= learning_proposition.name %></h1>
          <p><%= learning_proposition.session_date.strftime("%d/%m/%Y %H:%M")%></p>
          <p><%= truncate(learning_proposition.description, length: 180) %></p>
          <p><%= link_to "SAIBA MAIS", learning_proposition_path(learning_proposition.id), class: "btn btn-success btn_saiba_mais" %></td></p>
        </div>
    <% end %>

app/views/learning_propositions/create.html.erb
Criado!

app/views/learning_propositions/index.html.erb
<div class="container">
  <div class="row" id="abertas">
    <h2>Proposições Abertas</h2>
    <%= render "list", learning_propositions: @learning_propositions_open %>
  </div>
  <div class="row" style="margin-top:50px">
    <h2>Proposições Fechadas</h2>
    <%= render "list", learning_propositions: @learning_propositions_close  %>
  </div>
</div>

app/views/learning_propositions/new.html.erb
  <div class="row">
    <div class="container-form">

      <div class="col-lg-12 text-center title-page">
        <h1>CRIAR SESSÃO DE APRENDIZAGEM</h1>
      </div>

      <%= simple_form_for @learning_proposition do |f| %>
        <%= f.error_notification %>
        <div class="form-group">
          <%= f.text_field :name, class: "form-control input-lg", placeholder: "Tema da Sessão de Aprendizagem. Ex: Gestão Ágil de Projetos com Scrum"%>
        </div>
        <div class="form-group">
          <%= f.text_area :description, class:"form-control", placeholder:"Descrição do Tema", rows:"3"%>
        </div>
        <div class="form-group">
          <div class="row">
            <div class="col-md-6">
              <%= f.text_field :min_attendees, class: "form-control input-lg", placeholder: "Numero mínimo de participantes"%>
            </div>
            <div class="col-md-6">
              <%= f.text_field :max_attendees, class: "form-control input-lg", placeholder: "Numero maximo de participantes"%>
            </div>
          </div>
        </div>
        <div class="form-group">
          <%= f.text_field :location, class: "form-control input-lg", placeholder: "Local"%>
        </div>
        <div class="form-group">
          <div class="row">
            <div class="col-md-6">
              <%= f.text_field :session_date, class: "form-control input-lg", placeholder: "Data e Hora"%>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="row">
            <div class="col-md-6">
              <%= f.password_field :password, class: "form-control input-lg", placeholder: "Senha"%>
            </div>
            <div class="col-md-6">
              <%= content_tag :div, "Obs.: Esta senha pode ser usada para eventual exclusão desta sessão", class: "password_label"%>
            </div>
          </div>
        </div>
        <%= f.submit "CRIAR SESSÃO", class:"btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/learning_propositions/show.html.erb
<ol class="breadcrumb">
  <li><a href="#">Home</a></li>
  <li class="active">Data</li>
</ol>

<div class="box-detail">
  <!-- Default panel contents -->
  <div class="panel-heading">
    <h2><%= @learning_proposition.name%></h2>
    <p><%= @learning_proposition.location%></p>
    <p><%= l(@learning_proposition.session_date)%></p>
  </div>

  <div class="panel-interests">
    <!--
    <span class="numero_interessados" type="button">
      Pessoas interessadas: <span class="badge numero_interessados"><%= @learning_proposition.interests.size %></span>
    </span>
  -->
  </div>

  <div class="">
    <%= link_to("INCREVER-SE AGORA", new_learning_proposition_interest_url(@learning_proposition), {class:"btn btn-orange"})  %>
  </div>
  <!-- Table -->
</div>

<div class="descricao">

  <h3>O Tema:</h3>
  <p>
    <%= @learning_proposition.description%>
  </p>

</div>
<% if @learning_proposition.interests.size == 0 %>
  <div class="divisor"></div>
  <div class="row">
    <div class="col-md-4">
    <%= form_tag(learning_proposition_path, method: "delete") do %>
      <%= label_tag(:password, "Insira a senha para excluir esta sessão " + @learning_proposition.name) %>
      <%= password_field_tag("learning_proposition[password]", nil, class: 'form-control', placeholder:'Senha') %>
      <%= hidden_field_tag("learning_proposition[id]",@learning_proposition.id) %>
      <%= submit_tag("Excluir Sessão",class: 'btn btn-default') %>
    <% end %>
    </div>
  </div>

<% else %>

    <h3>Interessados nessa sessão
    <span class="badge numero_interessados"><%= @learning_proposition.interests.size %></span>
  </span></h3>
    <table class="table table-condensed tabela_interessados">
      <tr>
        <th>NOME</th>
        <th>E-MAIL</th>
      </tr>
      <% @learning_proposition.interests.each do |interests| %>
        <tr>
          <td><%= interests.name %>
          </td>
          <td><%= interests.email %></span></td>
        </tr>
      <% end %>
    </table>
<% end %>